version: '3'

services:
    proxy:
        image: likesistemas/nginx-reverse:latest
        build: 
            context: .
        environment:
            - BACKEND_SERVER=${BACKEND_SERVER:-https\:\/\/eichefe.com.br\/}
        ports:
            - ${PORT:-8080}:80